mkdir /mnt/ams2/SD
mkdir /mnt/ams2/HD
mkdir /mnt/ams2/SD/proc
mkdir /mnt/ams2/SD/proc/daytime
mkdir /mnt/ams2/meteors
mkdir /mnt/ams2/saved
mkdir /mnt/ams2/saved/planes
mkdir /mnt/ams2/saved/sats
mkdir /mnt/ams2/saved/interesting
mkdir /mnt/ams2/cal
mkdir /mnt/ams2/cal/solved
mkdir /mnt/ams2/cal/failed
mkdir /mnt/ams2/cal/bad
